name: my first

on:
  push:
    branches: 
      - main

jobs: 
  FirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Du Ma"
      - name: List files in repository
        uses: actions/checkout@v4.2.2
      - run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
  
